Riverton_Town_House_2_MapScripts::
	.byte 0

Riverton_Town_House_2_EventScript_InventorTheo::
	msgbox Riverton_Town_House_2_Text_InventorTheo, MSGBOX_NPC
	end

Riverton_Town_House_2_Text_InventorTheo:
	.string "Ah, a visitor! Welcome to my workshop.\n"
	.string "I'm working on a prototype engine for\l"
	.string "boats.\p"
	.string "If you find any rare components, do let\n"
	.string "me know-I might just have something\l"
	.string "for you!$"