Route102_EventScript_Calvin
Route102_EventScript_Rick
Route102_EventScript_Allen
Route102_EventScript_Tiana
Route104_EventScript_Billy
Route104_EventScript_Darian
PetalburgWoods_EventScript_Lyle
PetalburgWoods_EventScript_James
Route104_EventScript_Winston
Route104_EventScript_Haley
Route104_EventScript_Gina
Route104_EventScript_Ivan

RustboroCity_Gym_EventScript_Tommy
RustboroCity_Gym_EventScript_Marc
RustboroCity_Gym_EventScript_Josh

Route116_EventScript_Joey
Route116_EventScript_Jose
Route116_EventScript_Johnson
Route116_EventScript_Clark
Route116_EventScript_Devan
Route116_EventScript_Jerry
Route116_EventScript_Janice
Route116_EventScript_Sarah
Route116_EventScript_Dawson

Route106_EventScript_Ned
Route106_EventScript_Elliot


EventScript_RaintreeIsland_FireRoom_GymTrainer1
EventScript_RaintreeIsland_IceRoom_GymTrainer2
EventScript_RaintreeIsland_FireRoom_GymTrainer3
EventScript_RaintreeIsland_IceRoom_GymTrainer4
EventScript_RaintreeIsland_FireRoom_GymTrainer5

Route109_EventScript_Huey
Route109_EventScript_Hailey
Route109_EventScript_Edmond
Route109_EventScript_Ricky
Route109_EventScript_Lola
Route109_EventScript_Chandler
Route109_SeashoreHouse_EventScript_Dwayne
Route109_SeashoreHouse_EventScript_Johanna
Route109_SeashoreHouse_EventScript_Simon

Route110_EventScript_Isabel
Route110_EventScript_Kaleb
Route110_EventScript_Timmy
Route110_TrickHousePuzzle1_EventScript_Sally
Route110_TrickHousePuzzle1_EventScript_Robin
Route110_TrickHousePuzzle1_EventScript_Eddie
Route103_EventScript_Daisy
Route103_EventScript_Liv
Route103_EventScript_Miguel
Route103_EventScript_Andrew
Route110_EventScript_Jacob
Route110_EventScript_Jasmine
Route110_EventScript_Benjamin
Route110_EventScript_Anthony
Route110_EventScript_Abigail
Route110_EventScript_Joseph
Route110_EventScript_Alyssa
Route110_EventScript_Edward
Route110_EventScript_Dale
Route117_EventScript_Dylan
Route117_EventScript_Meg
Route117_EventScript_Isaac
Route117_EventScript_Maria
Route117_EventScript_Aisha
Route117_EventScript_Melina
Route117_EventScript_Brandi
Route117_EventScript_Derek
Route117_EventScript_Lydia

