#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_MAY         0
#define MUGSHOT_SIDNEY      1
#define MUGSHOT_PHOEBE      2
#define MUGSHOT_GLACIA      3
#define MUGSHOT_DRAKE       4
#define MUGSHOT_CHAMPION    5
#define MUGSHOT_JOHNM       6
#define MUGSHOT_WASULA      7
#define MUGSHOT_COLANGELO   8
#define MUGSHOT_OFFICE_DWIGHT 9
#define MUGSHOT_GRANT_HASELEY 10
#define MUGSHOT_JERETT      11


#define MUGSHOTS_COUNT      12

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H
