#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_MAY             0
#define MUGSHOT_SIDNEY          1
#define MUGSHOT_PHOEBE          2
#define MUGSHOT_GLACIA          3
#define MUGSHOT_DRAKE           4
#define MUGSHOT_CHAMPION        5
#define MUGSHOT_JOHNM           6
#define MUGSHOT_WASULA          7
#define MUGSHOT_COLANGELO       8
#define MUGSHOT_OFFICE_DWIGHT   9
#define MUGSHOT_GRANT_HASELEY   10
#define MUGSHOT_JERETT          11
#define MUGSHOT_OFFICE_JIM      12
#define MUGSHOT_DAWSON          13
#define MUGSHOT_LATTKA          14
#define MUGSHOT_MARRIOTT        15
#define MUGSHOT_MESSENGER       16
#define MUGSHOT_CIOTUSZYNSKI    17
#define MUGSHOT_HAIGH           18
#define MUGSHOT_OFFICE_MICHAEL  19
#define MUGSHOT_OFFICE_PAM      20
#define MUGSHOT_SHAWN_HASELEY   21
#define MUGSHOT_WES_THOMPSON     22
#define MUGSHOT_ZENDANO         23
#define MUGSHOT_CHADANDMARK    24

#define MUGSHOTS_COUNT      

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H
