#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

#define MUGSHOT_AMNEET 0
#define MUGSHOT_ANGELINA 1
#define MUGSHOT_BOBBY 2
#define MUGSHOT_JOHN 3
#define MUGSHOT_TILYOU 4
#define MUGSHOT_SEARS_PA 5
#define MUGSHOT_SEARS_TREASURE_MAP 6


#endif