gText_Birch_Welcome:: @ 82C897B
	.string "Ahoy Matey!\p"
	.string "It sure is good to see you made it to\n" 
	.string "Cinnabar Island without much trouble.\p"
	.string "I'm Peter. I work for the\n"
	.string "Natical Communication Center, in the\l"
	.string "Research and Development department.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is the Pokémon! I've\ndiscovered.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "The world as we know it\n"
	.string "will never be the same.\p"
	.string "This scientific breakthrough will\n"
	.string "go down in history as the best\lever.\p"
	.string "The democrats will try to take\n"
	.string "credit for this. But it was\l"
	.string "me, your president who made\l"
	.string "this discovery.\p"
	.string "I look at this Pokémon,\n"
	.string "discovered by the greatest people,\l"
	.string "and think how strong it must be.\p"
	.string "Very Strong.\p"
	.string "We will undertake research and\n"
	.string "make sure the U.S, the greatest\l"
	.string "nation made up of the greatest,\l"
	.string "strongest, most intelligent\l"
	.string "peoples in history will lead the\l"
	.string "field on PokéResearch.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "The people want Pokémon!\p"
	.string "$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "I'm sorry, I never got your name.$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"
	

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Nice to meet you {PLAYER}{KUN}!\p"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "We've been waiting for your arrival.\n"
	.string "The shipment you're carrying contains\l"
	.string "some components that are essential to\l"
	.string "advance our research. Thank you for\l"
	.string "bringing them with such haste.\p"
	.string "It must have been a long day at sea\n"
	.string "for you, coming all the way from\l"
	.string "Plaglaci Town, but if I could ask\l"
	.string "a small favor of you before you\l"
	.string "settle down for the night?\p"
	.string "Would you mind dropping the\n"
	.string "components with our receptionist at\l"
	.string "the Nautical Communication Center?\p"
	.string "Oh you will? Thank you so much!\p"
	.string "I hope you enjoy your stay on\n"
	.string "Cinnabar Island. There are plenty\l"
	.string "of sights to see!$"