gText_Birch_Welcome:: @ 82C897B
	.string "Breaking News!\p"
	.string "Here at channel 4 we're tuning in \nwith President Trump. He has an\limportant announcment to make!\p"
	.string "Hi there. Im President Trump. I am\npleased to announce that I have\ldiscovered the worlds first Pokémon\p"
	.string "That's right, creatures we thought \n"
	.string "were just part of a game are \lactually real!\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is the Pokémon! I've\ndiscovered.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "The world as we know it\n"
	.string "will never be the same.\p"
	.string "This scientific breakthrough will\n"
	.string "go down in history as the best\lever.\p"
	.string "The democrats will try to take\n"
	.string "credit for this. But it was\l"
	.string "me, your president who made\l"
	.string "this discovery.\p"
	.string "I look at this Pokémon,\n"
	.string "discovered by the greatest people,\l"
	.string "and think how strong it must be.\p"
	.string "Very Strong.\p"
	.string "We will undertake research and\n"
	.string "make sure the U.S, the greatest\l"
	.string "nation made up of the greatest,\l"
	.string "strongest, most intelligent\l"
	.string "peoples in history will lead the\l"
	.string "field on PokéResearch.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "The people want Pokémon!\p"
	.string "$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "And that's what I gave them!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "I have no doubt we will use\n"
	.string "this to help make America great\l"
	.string "again.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon with your fellow\l"
	.string "americans!\p"
	.string "$"