VermillionCity_House2_MapScripts::
	.byte 0

VermillionCity_House2_EventScript_ResidentLeo::
	msgbox VermillionCity_House2_Text_ResidentLeo, MSGBOX_NPC
	end

VermillionCity_House2_EventScript_ResidentNora::
	msgbox VermillionCity_House2_Text_ResidentNora, MSGBOX_NPC
	end

VermillionCity_House2_Text_ResidentLeo:
	.string "Living near the beach is a dream.\n"
	.string "I take my Pokémon swimming every morning!$"

VermillionCity_House2_Text_ResidentNora:
	.string "The Electric-type gym here is amazing!\n"
	.string "I've been training my Pikachu to take it on.$"