SaltLakeCityHouse1_MapScripts::
	.byte 0

SaltLakeCity_House1_EventScript_Woman::
	msgbox SaltLakeCity_House1_Text_HistoricalSaltLake, MSGBOX_NPC
	end


SaltLakeCity_House1_Text_HistoricalSaltLake:
	.string "Salt Lake City got its name\n"
	.string "from the nearby Great Salt Lake. It's\l"
	.string "a marvel of nature and history!\p"
	.string "The lake is so salty that it's\n"
	.string "almost impossible to sink. People\l"
	.string "come from all over to see it!$"
