CinnabarIslandHouse1Post_MapScripts::
	.byte 0

CinnabarIslandHouse1Post_EventScript_Student1::
	msgbox CinnabarIslandHouse1Post_Text_Student1, MSGBOX_DEFAULT
	closemessage
	end

CinnabarIslandHouse1Post_EventScript_Student2::
	msgbox CinnabarIslandHouse1Post_Text_Student2, MSGBOX_NPC
	end

CinnabarIslandHouse1Post_EventScript_Student3::
	msgbox CinnabarIslandHouse1Post_Text_Student3, MSGBOX_NPC
	end

CinnabarIslandHouse1Post_EventScript_Student4::
	msgbox CinnabarIslandHouse1Post_Text_Student4, MSGBOX_NPC
	end

CinnabarIslandHouse1Post_EventScript_Student5::
	msgbox CinnabarIslandHouse1Post_Text_Student5, MSGBOX_NPC
	closemessage
	end

CinnabarIslandHouse1Post_EventScript_Student6::
	msgbox CinnabarIslandHouse1Post_Text_Student6, MSGBOX_NPC
	end

CinnabarIslandHouse1Post_EventScript_Student7::
	msgbox CinnabarIslandHouse1Post_Text_Student7, MSGBOX_NPC
	end

@--------------------------------------------------------------------------------
@-------------------------------------Text---------------------------------------
@--------------------------------------------------------------------------------
@'''''''''''[______________________________________]

CinnabarIslandHouse1Post_Text_Student1:
	.string "I just woke up from our prof running\n"
	.string "outside. What the hell did I miss?$"

CinnabarIslandHouse1Post_Text_Student2:
	.string "I can't believe we are stuck on this\n"
	.string "stupid island! They have nothing fun\l"
	.string "here except the gym!$"

CinnabarIslandHouse1Post_Text_Student3:
	.string "Looks like clones can malfunction.\n"
	.string "Maybe he bought his PhD after all.$"

CinnabarIslandHouse1Post_Text_Student4:
	.string "Wow i think his Oxytocin level just\n"
	.string "made a hole in the floor. Are we\l"
	.string "really this incompetent?$"

CinnabarIslandHouse1Post_Text_Student5:
	.string "Well looks like I have to step up\n"
	.string "as a teacher now. I mean, I was the\l"
	.string "only one taking notes.$"

CinnabarIslandHouse1Post_Text_Student6:
	.string "SPRING BREAK! WOOOOOOO!\p"
	.string "...\p"
	.string "Seriously guys? Nobody wants to party?$"

CinnabarIslandHouse1Post_Text_Student7:
	.string "I think crystals and underground\n"
	.string "labs might be overrated. I will just\l"
	
	.string "enjoy the simple live and get some nice\l"
	.string "fried chicken.$"
