Riverton_Town_House_1_MapScripts::
	.byte 0


Riverton_Town_House_1_EventScript_LocalBob::
	msgbox Riverton_Town_House_1_Text_LocalBob, MSGBOX_NPC
	end

Riverton_Town_House_1_EventScript_SeagullLoverLynn::
	msgbox Riverton_Town_House_1_Text_SeagullLoverLynn, MSGBOX_NPC
	end

Riverton_Town_House_1_Text_LocalBob:
	.string "Been living here all my life. The harbor\n"
	.string "is the heart of Riverton, no doubt.\p"
	.string "What brings you here, stranger?$"

Riverton_Town_House_1_Text_SeagullLoverLynn:
	.string "The seagulls around here are just\n"
	.string "so fascinating! I could watch them\l"
	.string "all day long.$"