MAGM8DiaryEntry_EventScript_DiaryEntrySecond::
	lock
    finddiaryentry DIARY_ENTRY_SECOND
	finditem ITEM_DIARY_ENTRY, 1
	removeitem ITEM_DIARY_ENTRY
	msgbox MAGM8DiaryEntry_Text_FoundMissingDiaryEntry, MSGBOX_DEFAULT
	release
	end


MAGM8DiaryEntry_Text_FoundMissingDiaryEntry:
	.string "{PLAYER} found one of the missing pages\n"
	.string "from Professor Gooseberry's diary!\p"
	.string "{PLAYER} put the missing page back in\n"
	.string "the diary!$"

MAGM8DiaryEntry_Text_DiaryEntryFocusPunch_English:
	.string "I really need to Focus.\p"
	.string "I can't seem to find my way through\n"
	.string "these woods.\p"
	.string "It feels like a Punch in the gut.\p"
	.string "I guess I just have to keep my head\n"
	.string "Up and keep moving.$"

MAGM8DiaryEntry_Text_DiaryEntryDragonClaw_English:
	.string "There are lots of different Pokémon\n"
	.string "the deeper I get into these woods\p"
	.string "I think I even saw a Dragon type\n"
	.string "Pokémon Claw it's way out of a\l"
	.string "tree truck Up ahead.$"

MAGM8DiaryEntry_Text_DiaryEntryWaterPulse_English:
	.string "It's been a few days since I've had\n"
	.string "Water.\p"
	.string "My Pulse is weakening. I should have\n"
	.string "prepared for this better.\p"
	.string "I can't give Up.\n"
	.string "Not now.$"

MAGM8DiaryEntry_Text_DiaryEntryCalmMind_English:
	.string "I ran into a water-type Pokémon.\n"
	.string "It was kind enough to help hydrate\l"
	.string "me.\p"
	.string "I feel better. My Mind is Calm.\p"
	.string "I'm feeling all Right.\n"
	.string "I can do this.$"

MAGM8DiaryEntry_Text_DiaryEntryRoar_English:
	.string "As I get deeper into the woods the\n"
	.string "stranger things seem.\p"
	.string "I heard a loud Roar, and I'm not.\n"
	.string "sure where it came from.\p"
	.string "It shook me deep Down to my core.$"

MAGM8DiaryEntry_Text_DiaryEntryToxic_English:
	.string "There are so many cute little Spinarak\n"
	.string "in this area of the woods!\p"
	.string "I just hope I don't get bit. There is\n"
	.string "no one Up here and the wound could\l"
	.string "could be infected with Toxic poison.$"

MAGM8DiaryEntry_Text_DiaryEntryHail_English:
	.string "Well that is interesting. It started\n"
	.string "to Hail! It's really coming Down!\p"
	.string "This place sure is strange. I have\n"
	.string "lost track of time, but there is no\l"
	.string "way it could be winter yet.$"

MAGM8DiaryEntry_Text_DiaryEntryBulkUp_English:
	.string "The wild Pokémon seem to be few\n"
	.string "and far between.\p"
	.string "The ones that I do see are in Bulk\n"
	.string "season! Very healthy looking!\p"
	.string "In fact I saw a Stantler Down by\n"
    .string "the river who looked stronger than\l"
    .string "any I have ever seen before!.$"

MAGM8DiaryEntry_Text_DiaryEntryBulletSeed_English:
	.string "As I was traversing through the\n"
	.string "thick brush I saw something zip\l"
    .string "by me from Above\p"
	.string "It was so fast! Like a bullet!\p"
	.string "I've also seen some interesting\n"
	.string "Seeds in this area that I don't\l"
    .string "recognize.\p"
    .string "Once I get somewhere safe I will\n"
    .string "plant them and see what grows!.$"

MAGM8DiaryEntry_Text_DiaryEntryHiddenPower_English:
	.string "There is so much Hidden in these\n"
    .string "trees.\p"
    .string "I can feel a strange Power emanating\n"
    .string "from them.\p"
    .string "But I fear it is not as strong as it\n"
    .string "once was.\p"
    .string "Maybe we can someone harness what is\n"
    .string "Left of the trees energy.$"

MAGM8DiaryEntry_Text_DiaryEntrySunnyDay_English:
	.string "The weather goes from snow to Sunny,\n"
    .string "to foggy and damp.\p"
    .string "Right when I think I know what to\n"
    .string "expect, each Day brings new surprises.$"

MAGM8DiaryEntry_Text_DiaryEntryTaunt_English:
	.string "I'm so close to the end, I can feel\n"
    .string "the woods Taunting me.\p"
    .string "But I can't feel Down about it,\n"
    .string "I just have a feeling it is almost\l"
    .string "over.$"

MAGM8DiaryEntry_Text_DiaryEntryFocusPunch_Pokeprimer:
	.string "Testing Different Paths need to adjust language\p"
	.string "I really need to Focus.\p"
	.string "I can't seem to find my way through\n"
	.string "these woods.\p"
	.string "It feels like a Punch in the gut.\p"
	.string "I guess the only thing Left to do\n"
	.string "is keep moving.$"

MAGM8DiaryEntry_Text_FoundDiaryEntry:
	.string "You've found a missing page from\n"
	.string "Professor Gooseberry's Journal.\p"
	.string "Would you like to read it?$"
