CinnabarIsland_PostShipWreck_MapScripts::
	.byte 0


@--------------------------------------------------------------------------------
@------------------------------------Events--------------------------------------
@--------------------------------------------------------------------------------

CinnabarIsland_PostShipwreck_EventScript_Sailor::
	msgbox CinnabarIsland_PostShipwreck_Text_Sailor, MSGBOX_NPC
	end

@--------------------------------------------------------------------------------
@-------------------------------------Text---------------------------------------
@--------------------------------------------------------------------------------


CinnabarIsland_PostShipwreck_Text_Sailor:
	.string "Our ship... Who would do\n"
	.string "this?\p"
	.string "How are we going to get home now?\n"
	.string "I knew staying overnight was a bad\l"
	.string "idea.$"