	.align 2
gTileset_General:: @ 83DF704
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_General
	.4byte gTilesetPalettes_General
	.4byte gMetatiles_General
	.4byte gMetatileAttributes_General
	.4byte InitTilesetAnim_General

	.align 2
gTileset_Petalburg:: @ 83DF71C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Petalburg
	.4byte gTilesetPalettes_Petalburg
	.4byte gMetatiles_Petalburg
	.4byte gMetatileAttributes_Petalburg
	.4byte InitTilesetAnim_Petalburg

	.align 2
gTileset_Rustboro:: @ 83DF734
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Rustboro
	.4byte gTilesetPalettes_Rustboro
	.4byte gMetatiles_Rustboro
	.4byte gMetatileAttributes_Rustboro
	.4byte InitTilesetAnim_Rustboro

	.align 2
gTileset_Dewford:: @ 83DF74C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Dewford
	.4byte gTilesetPalettes_Dewford
	.4byte gMetatiles_Dewford
	.4byte gMetatileAttributes_Dewford
	.4byte InitTilesetAnim_Dewford

	.align 2
gTileset_Slateport:: @ 83DF764
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Slateport
	.4byte gTilesetPalettes_Slateport
	.4byte gMetatiles_Slateport
	.4byte gMetatileAttributes_Slateport
	.4byte InitTilesetAnim_Slateport

	.align 2
gTileset_Mauville:: @ 83DF77C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mauville
	.4byte gTilesetPalettes_Mauville
	.4byte gMetatiles_Mauville
	.4byte gMetatileAttributes_Mauville
	.4byte InitTilesetAnim_Mauville

	.align 2
gTileset_Lavaridge:: @ 83DF794
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lavaridge
	.4byte gTilesetPalettes_Lavaridge
	.4byte gMetatiles_Lavaridge
	.4byte gMetatileAttributes_Lavaridge
	.4byte InitTilesetAnim_Lavaridge

	.align 2
gTileset_Fallarbor:: @ 83DF7AC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Fallarbor
	.4byte gTilesetPalettes_Fallarbor
	.4byte gMetatiles_Fallarbor
	.4byte gMetatileAttributes_Fallarbor
	.4byte InitTilesetAnim_Fallarbor

	.align 2
gTileset_Fortree:: @ 83DF7C4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Fortree
	.4byte gTilesetPalettes_Fortree
	.4byte gMetatiles_Fortree
	.4byte gMetatileAttributes_Fortree
	.4byte InitTilesetAnim_Fortree

	.align 2
gTileset_Lilycove:: @ 83DF7DC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lilycove
	.4byte gTilesetPalettes_Lilycove
	.4byte gMetatiles_Lilycove
	.4byte gMetatileAttributes_Lilycove
	.4byte InitTilesetAnim_Lilycove

	.align 2
gTileset_Mossdeep:: @ 83DF7F4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mossdeep
	.4byte gTilesetPalettes_Mossdeep
	.4byte gMetatiles_Mossdeep
	.4byte gMetatileAttributes_Mossdeep
	.4byte InitTilesetAnim_Mossdeep

	.align 2
gTileset_EverGrande:: @ 83DF80C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_EverGrande
	.4byte gTilesetPalettes_EverGrande
	.4byte gMetatiles_EverGrande
	.4byte gMetatileAttributes_EverGrande
	.4byte InitTilesetAnim_EverGrande

	.align 2
gTileset_Pacifidlog:: @ 83DF824
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Pacifidlog
	.4byte gTilesetPalettes_Pacifidlog
	.4byte gMetatiles_Pacifidlog
	.4byte gMetatileAttributes_Pacifidlog
	.4byte InitTilesetAnim_Pacifidlog

	.align 2
gTileset_Sootopolis:: @ 83DF83C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Sootopolis
	.4byte gTilesetPalettes_Sootopolis
	.4byte gMetatiles_Sootopolis
	.4byte gMetatileAttributes_Sootopolis
	.4byte InitTilesetAnim_Sootopolis

	.align 2
gTileset_BattleFrontierOutsideWest:: @ 83DF854
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierOutsideWest
	.4byte gTilesetPalettes_BattleFrontierOutsideWest
	.4byte gMetatiles_BattleFrontierOutsideWest
	.4byte gMetatileAttributes_BattleFrontierOutsideWest
	.4byte InitTilesetAnim_BattleFrontierOutsideWest

	.align 2
gTileset_BattleFrontierOutsideEast:: @ 83DF86C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierOutsideEast
	.4byte gTilesetPalettes_BattleFrontierOutsideEast
	.4byte gMetatiles_BattleFrontierOutsideEast
	.4byte gMetatileAttributes_BattleFrontierOutsideEast
	.4byte InitTilesetAnim_BattleFrontierOutsideEast

	.align 2
gTileset_Building:: @ 83DF884
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideBuilding
	.4byte gTilesetPalettes_InsideBuilding
	.4byte gMetatiles_InsideBuilding
	.4byte gMetatileAttributes_InsideBuilding
	.4byte InitTilesetAnim_Building

	.align 2
gTileset_Shop:: @ 83DF89C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Shop
	.4byte gTilesetPalettes_Shop
	.4byte gMetatiles_Shop
	.4byte gMetatileAttributes_Shop
	.4byte NULL @ animation callback

	.align 2
gTileset_PokemonCenter:: @ 83DF8B4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonCenter
	.4byte gTilesetPalettes_PokemonCenter
	.4byte gMetatiles_PokemonCenter
	.4byte gMetatileAttributes_PokemonCenter
	.4byte NULL @ animation callback

	.align 2
gTileset_Cave:: @ 83DF8CC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Cave
	.4byte gTilesetPalettes_Cave
	.4byte gMetatiles_Cave
	.4byte gMetatileAttributes_Cave
	.4byte InitTilesetAnim_Cave

	.align 2
gTileset_PokemonSchool:: @ 83DF8E4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonSchool
	.4byte gTilesetPalettes_PokemonSchool
	.4byte gMetatiles_PokemonSchool
	.4byte gMetatileAttributes_PokemonSchool
	.4byte NULL @ animation callback

	.align 2
gTileset_PokemonFanClub:: @ 83DF8FC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonFanClub
	.4byte gTilesetPalettes_PokemonFanClub
	.4byte gMetatiles_PokemonFanClub
	.4byte gMetatileAttributes_PokemonFanClub
	.4byte NULL @ animation callback

	.align 2
gTileset_Unused1:: @ 83DF914
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Unused1
	.4byte gTilesetPalettes_Unused1
	.4byte gMetatiles_Unused1
	.4byte gMetatileAttributes_Unused1
	.4byte NULL @ animation callback

	.align 2
gTileset_MeteorFalls:: @ 83DF92C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MeteorFalls
	.4byte gTilesetPalettes_MeteorFalls
	.4byte gMetatiles_MeteorFalls
	.4byte gMetatileAttributes_MeteorFalls
	.4byte NULL @ animation callback

	.align 2
gTileset_OceanicMuseum:: @ 83DF944
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_OceanicMuseum
	.4byte gTilesetPalettes_OceanicMuseum
	.4byte gMetatiles_OceanicMuseum
	.4byte gMetatileAttributes_OceanicMuseum
	.4byte NULL @ animation callback

	.align 2
gTileset_CableClub:: @ 83DF95C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_CableClub
	.4byte gTilesetPalettes_CableClub
	.4byte gMetatiles_CableClub
	.4byte gMetatileAttributes_CableClub
	.4byte NULL @ animation callback

	.align 2
gTileset_SeashoreHouse:: @ 83DF974
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SeashoreHouse
	.4byte gTilesetPalettes_SeashoreHouse
	.4byte gMetatiles_SeashoreHouse
	.4byte gMetatileAttributes_SeashoreHouse
	.4byte NULL @ animation callback

	.align 2
gTileset_PrettyPetalFlowerShop:: @ 83DF98C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PrettyPetalFlowerShop
	.4byte gTilesetPalettes_PrettyPetalFlowerShop
	.4byte gMetatiles_PrettyPetalFlowerShop
	.4byte gMetatileAttributes_PrettyPetalFlowerShop
	.4byte NULL @ animation callback

	.align 2
gTileset_PokemonDayCare:: @ 83DF9A4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonDayCare
	.4byte gTilesetPalettes_PokemonDayCare
	.4byte gMetatiles_PokemonDayCare
	.4byte gMetatileAttributes_PokemonDayCare
	.4byte NULL @ animation callback

	.align 2
gTileset_Facility:: @ 83DF9BC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Facility
	.4byte gTilesetPalettes_Facility
	.4byte gMetatiles_Facility
	.4byte gMetatileAttributes_Facility
	.4byte NULL @ animation callback

	.align 2
gTileset_BikeShop:: @ 83DF9D4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BikeShop
	.4byte gTilesetPalettes_BikeShop
	.4byte gMetatiles_BikeShop
	.4byte gMetatileAttributes_BikeShop
	.4byte InitTilesetAnim_BikeShop

	.align 2
gTileset_RusturfTunnel:: @ 83DF9EC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RusturfTunnel
	.4byte gTilesetPalettes_RusturfTunnel
	.4byte gMetatiles_RusturfTunnel
	.4byte gMetatileAttributes_RusturfTunnel
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseBrownCave:: @ 83DFA04
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseBrownCave
	.4byte gTilesetPalettes_SecretBaseBrownCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseTree:: @ 83DFA1C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseTree
	.4byte gTilesetPalettes_SecretBaseTree
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseShrub:: @ 83DFA34
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseShrub
	.4byte gTilesetPalettes_SecretBaseShrub
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseBlueCave:: @ 83DFA4C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseBlueCave
	.4byte gTilesetPalettes_SecretBaseBlueCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseYellowCave:: @ 83DFA64
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseYellowCave
	.4byte gTilesetPalettes_SecretBaseYellowCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseRedCave:: @ 83DFA7C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseRedCave
	.4byte gTilesetPalettes_SecretBaseRedCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_InsideOfTruck:: @ 83DFA94
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideOfTruck
	.4byte gTilesetPalettes_InsideOfTruck
	.4byte gMetatiles_InsideOfTruck
	.4byte gMetatileAttributes_InsideOfTruck
	.4byte NULL @ animation callback

	.align 2
gTileset_Unused2:: @ 83DFAAC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Unused2
	.4byte gTilesetPalettes_Unused2
	.4byte gMetatiles_Unused2
	.4byte gMetatileAttributes_Unused2
	.4byte NULL @ animation callback

	.align 2
gTileset_Contest:: @ 83DFAC4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Contest
	.4byte gTilesetPalettes_Contest
	.4byte gMetatiles_Contest
	.4byte gMetatileAttributes_Contest
	.4byte NULL @ animation callback

	.align 2
gTileset_LilycoveMuseum:: @ 83DFADC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_LilycoveMuseum
	.4byte gTilesetPalettes_LilycoveMuseum
	.4byte gMetatiles_LilycoveMuseum
	.4byte gMetatileAttributes_LilycoveMuseum
	.4byte NULL @ animation callback

	.align 2
gTileset_BrendansMaysHouse:: @ 83DFAF4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BrendansMaysHouse
	.4byte gTilesetPalettes_BrendansMaysHouse
	.4byte gMetatiles_BrendansMaysHouse
	.4byte gMetatileAttributes_BrendansMaysHouse
	.4byte NULL @ animation callback

	.align 2
gTileset_Lab:: @ 83DFB0C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lab
	.4byte gTilesetPalettes_Lab
	.4byte gMetatiles_Lab
	.4byte gMetatileAttributes_Lab
	.4byte NULL @ animation callback

	.align 2
gTileset_Underwater:: @ 83DFB24
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Underwater
	.4byte gTilesetPalettes_Underwater
	.4byte gMetatiles_Underwater
	.4byte gMetatileAttributes_Underwater
	.4byte InitTilesetAnim_Underwater

	.align 2
gTileset_PetalburgGym:: @ 83DFB3C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PetalburgGym
	.4byte gTilesetPalettes_PetalburgGym
	.4byte gMetatiles_PetalburgGym
	.4byte gMetatileAttributes_PetalburgGym
	.4byte NULL @ animation callback

	.align 2
gTileset_SootopolisGym:: @ 83DFB54
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SootopolisGym
	.4byte gTilesetPalettes_SootopolisGym
	.4byte gMetatiles_SootopolisGym
	.4byte gMetatileAttributes_SootopolisGym
	.4byte InitTilesetAnim_SootopolisGym

	.align 2
gTileset_GenericBuilding:: @ 83DFB6C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_GenericBuilding
	.4byte gTilesetPalettes_GenericBuilding
	.4byte gMetatiles_GenericBuilding
	.4byte gMetatileAttributes_GenericBuilding
	.4byte NULL @ animation callback

	.align 2
gTileset_MauvilleGameCorner:: @ 83DFB84
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MauvilleGameCorner
	.4byte gTilesetPalettes_MauvilleGameCorner
	.4byte gMetatiles_MauvilleGameCorner
	.4byte gMetatileAttributes_MauvilleGameCorner
	.4byte NULL @ animation callback

	.align 2
gTileset_RustboroGym:: @ 83DFB9C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RustboroGym
	.4byte gTilesetPalettes_RustboroGym
	.4byte gMetatiles_RustboroGym
	.4byte gMetatileAttributes_RustboroGym
	.4byte NULL @ animation callback

	.align 2
gTileset_DewfordGym:: @ 83DFBB4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_DewfordGym
	.4byte gTilesetPalettes_DewfordGym
	.4byte gMetatiles_DewfordGym
	.4byte gMetatileAttributes_DewfordGym
	.4byte NULL @ animation callback

	.align 2
gTileset_MauvilleGym:: @ 83DFBCC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MauvilleGym
	.4byte gTilesetPalettes_MauvilleGym
	.4byte gMetatiles_MauvilleGym
	.4byte gMetatileAttributes_MauvilleGym
	.4byte InitTilesetAnim_MauvilleGym

	.align 2
gTileset_LavaridgeGym:: @ 83DFBE4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_LavaridgeGym
	.4byte gTilesetPalettes_LavaridgeGym
	.4byte gMetatiles_LavaridgeGym
	.4byte gMetatileAttributes_LavaridgeGym
	.4byte NULL @ animation callback

	.align 2
gTileset_TrickHousePuzzle:: @ 83DFBFC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrickHousePuzzle
	.4byte gTilesetPalettes_TrickHousePuzzle
	.4byte gMetatiles_TrickHousePuzzle
	.4byte gMetatileAttributes_TrickHousePuzzle
	.4byte NULL @ animation callback

	.align 2
gTileset_FortreeGym:: @ 83DFC14
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_FortreeGym
	.4byte gTilesetPalettes_FortreeGym
	.4byte gMetatiles_FortreeGym
	.4byte gMetatileAttributes_FortreeGym
	.4byte NULL @ animation callback

	.align 2
gTileset_MossdeepGym:: @ 83DFC2C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MossdeepGym
	.4byte gTilesetPalettes_MossdeepGym
	.4byte gMetatiles_MossdeepGym
	.4byte gMetatileAttributes_MossdeepGym
	.4byte NULL @ animation callback

	.align 2
gTileset_InsideShip:: @ 83DFC44
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideShip
	.4byte gTilesetPalettes_InsideShip
	.4byte gMetatiles_InsideShip
	.4byte gMetatileAttributes_InsideShip
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBase:: @ 83DFC5C
	.byte FALSE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBase
	.4byte gTilesetPalettes_SecretBase
	.4byte gMetatiles_SecretBasePrimary
	.4byte gMetatileAttributes_SecretBasePrimary
	.4byte NULL @ animation callback

	.align 2
gTilesetPointer_SecretBase:: @ 83DFC74
	.4byte gTileset_SecretBase

	.align 2
gTilesetPointer_SecretBaseRedCave:: @ 83DFC78
	.4byte gTileset_SecretBaseRedCave

	.align 2
gTileset_EliteFour:: @ 83DFC7C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_EliteFour
	.4byte gTilesetPalettes_EliteFour
	.4byte gMetatiles_EliteFour
	.4byte gMetatileAttributes_EliteFour
	.4byte InitTilesetAnim_EliteFour

	.align 2
gTileset_BattleFrontier:: @ 83DFC94
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontier
	.4byte gTilesetPalettes_BattleFrontier
	.4byte gMetatiles_BattleFrontier
	.4byte gMetatileAttributes_BattleFrontier
	.4byte NULL @ animation callback

	.align 2
gTileset_BattlePalace:: @ 83DFCAC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePalace
	.4byte gTilesetPalettes_BattlePalace
	.4byte gMetatiles_BattlePalace
	.4byte gMetatileAttributes_BattlePalace
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleDome:: @ 83DFCC4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleDome
	.4byte gTilesetPalettes_BattleDome
	.4byte gMetatiles_BattleDome
	.4byte gMetatileAttributes_BattleDome
	.4byte InitTilesetAnim_BattleDome

	.align 2
gTileset_BattleFactory:: @ 83DFCDC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFactory
	.4byte gTilesetPalettes_BattleFactory
	.4byte gMetatiles_BattleFactory
	.4byte gMetatileAttributes_BattleFactory
	.4byte NULL @ animation callback

	.align 2
gTileset_BattlePike:: @ 83DFCF4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePike
	.4byte gTilesetPalettes_BattlePike
	.4byte gMetatiles_BattlePike
	.4byte gMetatileAttributes_BattlePike
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleArena:: @ 83DFD0C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleArena
	.4byte gTilesetPalettes_BattleArena
	.4byte gMetatiles_BattleArena
	.4byte gMetatileAttributes_BattleArena
	.4byte NULL @ animation callback

	.align 2
gTileset_BattlePyramid:: @ 83DFD24
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePyramid
	.4byte gTilesetPalettes_BattlePyramid
	.4byte gMetatiles_BattlePyramid
	.4byte gMetatileAttributes_BattlePyramid
	.4byte InitTilesetAnim_BattlePyramid

	.align 2
gTileset_MirageTower:: @ 83DFD3C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MirageTower
	.4byte gTilesetPalettes_MirageTower
	.4byte gMetatiles_MirageTower
	.4byte gMetatileAttributes_MirageTower
	.4byte NULL @ animation callback

	.align 2
gTileset_MossdeepGameCorner:: @ 83DFD54
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MossdeepGameCorner
	.4byte gTilesetPalettes_MossdeepGameCorner
	.4byte gMetatiles_MossdeepGameCorner
	.4byte gMetatileAttributes_MossdeepGameCorner
	.4byte NULL @ animation callback

	.align 2
gTileset_IslandHarbor:: @ 83DFD6C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_IslandHarbor
	.4byte gTilesetPalettes_IslandHarbor
	.4byte gMetatiles_IslandHarbor
	.4byte gMetatileAttributes_IslandHarbor
	.4byte NULL @ animation callback

	.align 2
gTileset_TrainerHill:: @ 83DFD84
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrainerHill
	.4byte gTilesetPalettes_TrainerHill
	.4byte gMetatiles_TrainerHill
	.4byte gMetatileAttributes_TrainerHill
	.4byte NULL @ animation callback

	.align 2
gTileset_NavelRock:: @ 83DFD9C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_NavelRock
	.4byte gTilesetPalettes_NavelRock
	.4byte gMetatiles_NavelRock
	.4byte gMetatileAttributes_NavelRock
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleFrontierRankingHall:: @ 83DFDB4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierRankingHall
	.4byte gTilesetPalettes_BattleFrontierRankingHall
	.4byte gMetatiles_BattleFrontierRankingHall
	.4byte gMetatileAttributes_BattleFrontierRankingHall
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleTent:: @ 83DFDCC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleTent
	.4byte gTilesetPalettes_BattleTent
	.4byte gMetatiles_BattleTent
	.4byte gMetatileAttributes_BattleTent
	.4byte NULL @ animation callback

	.align 2
gTileset_MysteryEventsHouse:: @ 83DFDE4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MysteryEventsHouse
	.4byte gTilesetPalettes_MysteryEventsHouse
	.4byte gMetatiles_MysteryEventsHouse
	.4byte gMetatileAttributes_MysteryEventsHouse
	.4byte NULL @ animation callback

	.align 2
gTileset_UnionRoom:: @ 83DFDFC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_UnionRoom
	.4byte gTilesetPalettes_UnionRoom
	.4byte gMetatiles_UnionRoom
	.4byte gMetatileAttributes_UnionRoom
	.4byte NULL @ animation callback

	.align 2
gTileset_LakeMeadVillage::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_LakeMeadVillage
	.4byte gTilesetPalettes_LakeMeadVillage
	.4byte gMetatiles_LakeMeadVillage
	.4byte gMetatileAttributes_LakeMeadVillage
	.4byte NULL

	.align 2
gTileset_WalmoreTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_WalmoreTown
	.4byte gTilesetPalettes_WalmoreTown
	.4byte gMetatiles_WalmoreTown
	.4byte gMetatileAttributes_WalmoreTown
	.4byte NULL

	.align 2
gTileset_SummitCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SummitCity
	.4byte gTilesetPalettes_SummitCity
	.4byte gMetatiles_SummitCity
	.4byte gMetatileAttributes_SummitCity
	.4byte NULL

	.align 2
gTileset_SummitGeneral::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SummitGeneral
	.4byte gTilesetPalettes_SummitGeneral
	.4byte gMetatiles_SummitGeneral
	.4byte gMetatileAttributes_SummitGeneral
	.4byte NULL

	.align 2
gTileset_LynchPark::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_LynchPark
	.4byte gTilesetPalettes_LynchPark
	.4byte gMetatiles_LynchPark
	.4byte gMetatileAttributes_LynchPark
	.4byte NULL

	.align 2
gTileset_GeneralSnow::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_GeneralSnow
	.4byte gTilesetPalettes_GeneralSnow
	.4byte gMetatiles_GeneralSnow
	.4byte gMetatileAttributes_GeneralSnow
	.4byte NULL

	.align 2
gTileset_GratwickPeaks::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_GratwickPeaks
	.4byte gTilesetPalettes_GratwickPeaks
	.4byte gMetatiles_GratwickPeaks
	.4byte gMetatileAttributes_GratwickPeaks
	.4byte NULL

	.align 2
gTileset_GratwickGraveyard::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_GratwickGraveyard
	.4byte gTilesetPalettes_GratwickGraveyard
	.4byte gMetatiles_GratwickGraveyard
	.4byte gMetatileAttributes_GratwickGraveyard
	.4byte NULL

	.align 2
gTileset_Raintree::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_Raintree
	.4byte gTilesetPalettes_Raintree
	.4byte gMetatiles_Raintree
	.4byte gMetatileAttributes_Raintree
	.4byte NULL

	.align 2
gTileset_GrandIslandBridge::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_GrandIslandBridge
	.4byte gTilesetPalettes_GrandIslandBridge
	.4byte gMetatiles_GrandIslandBridge
	.4byte gMetatileAttributes_GrandIslandBridge
	.4byte NULL

	.align 2
gTileset_SummitCityGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SummitCityGym
	.4byte gTilesetPalettes_SummitCityGym
	.4byte gMetatiles_SummitCityGym
	.4byte gMetatileAttributes_SummitCityGym
	.4byte NULL

	.align 2
gTileset_Cave2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_Cave2
	.4byte gTilesetPalettes_Cave2
	.4byte gMetatiles_Cave2
	.4byte gMetatileAttributes_Cave2
	.4byte NULL

	.align 2
gTileset_RaintreeIsland_Gym_Fire::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_RaintreeIsland_Gym_Fire
	.4byte gTilesetPalettes_RaintreeIsland_Gym_Fire
	.4byte gMetatiles_RaintreeIsland_Gym_Fire
	.4byte gMetatileAttributes_RaintreeIsland_Gym_Fire
	.4byte InitTilesetAnim_RaintreeIsland_Gym_Fire

	.align 2
gTileset_RaintreeIsland_Gym_Ice::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_RaintreeIsland_Gym_Ice
	.4byte gTilesetPalettes_RaintreeIsland_Gym_Ice
	.4byte gMetatiles_RaintreeIsland_Gym_Ice
	.4byte gMetatileAttributes_RaintreeIsland_Gym_Ice
	.4byte InitTilesetAnim_RaintreeIsland_Gym_Ice

	.align 2
gTileset_RaintreeIsland_Pokecenter_Interior::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_RaintreeIsland_Pokecenter_Interior
	.4byte gTilesetPalettes_RaintreeIsland_Pokecenter_Interior
	.4byte gMetatiles_RaintreeIsland_Pokecenter_Interior
	.4byte gMetatileAttributes_RaintreeIsland_Pokecenter_Interior
	.4byte NULL

	.align 2
gTileset_GrandIslandGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_GrandIslandGym
	.4byte gTilesetPalettes_GrandIslandGym
	.4byte gMetatiles_GrandIslandGym
	.4byte gMetatileAttributes_GrandIslandGym
	.4byte NULL

	.align 2
gTileset_SnowGeneral::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SnowGeneral
	.4byte gTilesetPalettes_SnowGeneral
	.4byte gMetatiles_SnowGeneral
	.4byte gMetatileAttributes_SnowGeneral
	.4byte NULL

	.align 2
gTileset_SnowSecondary::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SnowSecondary
	.4byte gTilesetPalettes_SnowSecondary
	.4byte gMetatiles_SnowSecondary
	.4byte gMetatileAttributes_SnowSecondary
	.4byte NULL

	.align 2
gTileset_NiagaraWoodsPrimary::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_NiagaraWoodsPrimary
	.4byte gTilesetPalettes_NiagaraWoodsPrimary
	.4byte gMetatiles_NiagaraWoodsPrimary
	.4byte gMetatileAttributes_NiagaraWoodsPrimary
	.4byte NULL

	.align 2
gTileset_NiagaraWoodsSecondary::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_NiagaraWoodsSecondary
	.4byte gTilesetPalettes_NiagaraWoodsSecondary
	.4byte gMetatiles_NiagaraWoodsSecondary
	.4byte gMetatileAttributes_NiagaraWoodsSecondary
	.4byte NULL

	.align 2
gTileset_NiagaraVillage::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_NiagaraVillage
	.4byte gTilesetPalettes_NiagaraVillage
	.4byte gMetatiles_NiagaraVillage
	.4byte gMetatileAttributes_NiagaraVillage
	.4byte NULL

	.align 2
gTileset_SnowCavePrimary::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SnowCavePrimary
	.4byte gTilesetPalettes_SnowCavePrimary
	.4byte gMetatiles_SnowCavePrimary
	.4byte gMetatileAttributes_SnowCavePrimary
	.4byte NULL

	.align 2
gTileset_SnowCaveSecondary::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SnowCaveSecondary
	.4byte gTilesetPalettes_SnowCaveSecondary
	.4byte gMetatiles_SnowCaveSecondary
	.4byte gMetatileAttributes_SnowCaveSecondary
	.4byte NULL

	.align 2
gTileset_HomesteadNorth::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_HomesteadNorth
	.4byte gTilesetPalettes_HomesteadNorth
	.4byte gMetatiles_HomesteadNorth
	.4byte gMetatileAttributes_HomesteadNorth
	.4byte NULL

	.align 2
gTileset_WesternApproach::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_WesternApproach
	.4byte gTilesetPalettes_WesternApproach
	.4byte gMetatiles_WesternApproach
	.4byte gMetatileAttributes_WesternApproach
	.4byte InitTilesetAnim_WesternApproach

	.align 2
gTileset_WesternApproachSpringCanyon::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_WesternApproachSpringCanyon
	.4byte gTilesetPalettes_WesternApproachSpringCanyon
	.4byte gMetatiles_WesternApproachSpringCanyon
	.4byte gMetatileAttributes_WesternApproachSpringCanyon
	.4byte NULL

	.align 2
gTileset_MarriottStudyingBackground::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_MarriottStudyingBackground
	.4byte gTilesetPalettes_MarriottStudyingBackground
	.4byte gMetatiles_MarriottStudyingBackground
	.4byte gMetatileAttributes_MarriottStudyingBackground
	.4byte NULL

	.align 2
gTileset_MarriottIntroFrame2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_MarriottIntroFrame2
	.4byte gTilesetPalettes_MarriottIntroFrame2
	.4byte gMetatiles_MarriottIntroFrame2
	.4byte gMetatileAttributes_MarriottIntroFrame2
	.4byte NULL

	.align 2
gTileset_MarriottIntroFrame3::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_MarriottIntroFrame3
	.4byte gTilesetPalettes_MarriottIntroFrame3
	.4byte gMetatiles_MarriottIntroFrame3
	.4byte gMetatileAttributes_MarriottIntroFrame3
	.4byte NULL

	.align 2
gTileset_MarriottIntroFrame4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_MarriottIntroFrame4
	.4byte gTilesetPalettes_MarriottIntroFrame4
	.4byte gMetatiles_MarriottIntroFrame4
	.4byte gMetatileAttributes_MarriottIntroFrame4
	.4byte NULL

	.align 2
gTileset_MarriottIntroFrame5::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_MarriottIntroFrame5
	.4byte gTilesetPalettes_MarriottIntroFrame5
	.4byte gMetatiles_MarriottIntroFrame5
	.4byte gMetatileAttributes_MarriottIntroFrame5
	.4byte NULL

	.align 2
gTileset_MarriottIntroFrame6::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_MarriottIntroFrame6
	.4byte gTilesetPalettes_MarriottIntroFrame6
	.4byte gMetatiles_MarriottIntroFrame6
	.4byte gMetatileAttributes_MarriottIntroFrame6
	.4byte NULL

	.align 2
gTileset_DekuTreePrimary::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_DekuTreePrimary
	.4byte gTilesetPalettes_DekuTreePrimary
	.4byte gMetatiles_DekuTreePrimary
	.4byte gMetatileAttributes_DekuTreePrimary
	.4byte NULL

	.align 2
gTileset_DekuTreeEntrance::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_DekuTreeEntrance
	.4byte gTilesetPalettes_DekuTreeEntrance
	.4byte gMetatiles_DekuTreeEntrance
	.4byte gMetatileAttributes_DekuTreeEntrance
	.4byte NULL

	.align 2
gTileset_CinnibarIsland_Primary::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CinnibarIsland_Primary
	.4byte gTilesetPalettes_CinnibarIsland_Primary
	.4byte gMetatiles_CinnibarIsland_Primary
	.4byte gMetatileAttributes_CinnibarIsland_Primary
	.4byte NULL

	.align 2
gTileset_CinnibarIsland_Secondary::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CinnibarIsland_Secondary
	.4byte gTilesetPalettes_CinnibarIsland_Secondary
	.4byte gMetatiles_CinnibarIsland_Secondary
	.4byte gMetatileAttributes_CinnibarIsland_Secondary
	.4byte NULL

	.align 2
gTileset_MountCinnabar_Primary::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_MountCinnabar_Primary
	.4byte gTilesetPalettes_MountCinnabar_Primary
	.4byte gMetatiles_MountCinnabar_Primary
	.4byte gMetatileAttributes_MountCinnabar_Primary
	.4byte InitTilesetAnim_MountCinnabar_Primary

	.align 2
gTileset_CinnabarIsland_Secondary_PostShipwreck::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CinnabarIsland_Secondary_PostShipwreck
	.4byte gTilesetPalettes_CinnabarIsland_Secondary_PostShipwreck
	.4byte gMetatiles_CinnabarIsland_Secondary_PostShipwreck
	.4byte gMetatileAttributes_CinnabarIsland_Secondary_PostShipwreck
	.4byte NULL
